# Generated by Django 5.0.4 on 2025-03-21 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(5)])),
                ('in_stock', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
