# Generated by Django 5.1.7 on 2025-05-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutinfo',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('UK', 'United Kingdom'), ('AU', 'Australia'), ('BG', 'Bulgaria')], max_length=20),
        ),
    ]
