# Generated by Django 5.0.4 on 2025-03-21 20:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_store', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutinfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
