# Generated by Django 5.1.6 on 2025-04-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_store', '0003_remove_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='existing-user', max_length=50),
            preserve_default=False,
        ),
    ]
