# Generated by Django 5.0.4 on 2025-03-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_store', '0004_remove_checkoutinfo_country_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutinfo',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('UK', 'United Kingdom'), ('AU', 'Australia')], max_length=2),
        ),
    ]
