# Generated by Django 5.1.6 on 2025-04-13 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_store', '0005_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutinfo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='checkoutinfo',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='checkoutinfo',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='checkoutinfo',
            name='name_on_card',
        ),
        migrations.RemoveField(
            model_name='checkoutinfo',
            name='payment_token',
        ),
    ]
